;;; package management
(source melpa)
(source gnu)
(source org)

(depends-on "cask")

;;; evil packages
(depends-on "evil-leader")
(depends-on "evil")
(depends-on "evil-jumper")
(depends-on "evil-surround")
(depends-on "evil-indent-textobject")
(depends-on "evil-visualstar")
(depends-on "evil-nerd-commenter")
(depends-on "evil-matchit")

;;; tools
(depends-on "magit")
(depends-on "ag")
(depends-on "pt")

(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "projectile")

(depends-on "company")
(depends-on "flycheck")

;;; themes
(depends-on "sublime-themes")
(depends-on "monokai-theme")

;;; modes
(depends-on "markdown-mode")
(depends-on "coffee-mode")
(depends-on "yaml-mode")
(depends-on "vimrc-mode")

; Elixir
(depends-on "alchemist")

; Ruby/Rails
(depends-on "inf-ruby")
(depends-on "projectile-rails")
(depends-on "robe")
(depends-on "rvm")

; .NET
(depends-on "csharp-mode")
(depends-on "omnisharp")
(depends-on "web-mode")
(depends-on "powershell")

(depends-on "emmet-mode")

;;; powerline
(depends-on "powerline")
(depends-on "powerline-evil")
